export const AUTHENTICATION_SUCCESSFUL = "AUTHENTICATION_SUCCESSFUL";
export const GET_AUTOLOADED_SETTINGS = "GET_AUTOLOADED_SETTINGS";
export const SETTING_UPDATED = "SETTING_UPDATED";
export const SET_TOPBAR_BUTTONS = "SET_TOPBAR_BUTTONS";